###########
# Plugins #
###########

gems:
    # JekyllRedirectFrom
    # https://github.com/jekyll/jekyll-redirect-from
    # Plugin that allows Jekyll posts and pages to have multiple URLs.
    - jekyll-redirect-from

##############
# Publishing #
##############

# Site URL
# The base protocol and hostname for the website
# Default: not set (this variable is only necessary for external systems)
url: "https://guide-opensuse.alionet.org"

###########
# Serving #
###########

# Base URL
# Serve the website from the given base URL (does not include hostname)
# Default: "" (website is at the root of the domain)
baseurl: ""

# For more info on the serve command options, please refer to
# http://jekyllrb.com/docs/configuration/
